// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUaND4mmqmftfokfS3Iq_Bz37XZ0n4Bsk',
    appId: '1:166311231769:web:12b2999a3d74a724bac588',
    messagingSenderId: '166311231769',
    projectId: 'app-tare1',
    authDomain: 'app-tare1.firebaseapp.com',
    databaseURL: 'https://app-tare1-default-rtdb.firebaseio.com',
    storageBucket: 'app-tare1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYXIioiQh98aidBB4goLdI84AkCiC8UY',
    appId: '1:166311231769:android:9f12fb7648604bd2bac588',
    messagingSenderId: '166311231769',
    projectId: 'app-tare1',
    databaseURL: 'https://app-tare1-default-rtdb.firebaseio.com',
    storageBucket: 'app-tare1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQhzl8BySJ99vlDsPhejrspMzUYJNVEWM',
    appId: '1:166311231769:web:df2f0d8e9a5afb49bac588',
    messagingSenderId: '166311231769',
    projectId: 'app-tare1',
    authDomain: 'app-tare1.firebaseapp.com',
    databaseURL: 'https://app-tare1-default-rtdb.firebaseio.com',
    storageBucket: 'app-tare1.firebasestorage.app',
  );
}
